apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_HOSTNAME: 'auth.uninastream.ddnsfree.com'
  KC_HOSTNAME_STRICT: 'false'
  KC_HOSTNAME_STRICT_HTTPS: 'false'
  KC_PROXY: 'edge'
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  KEYCLOAK_ADMIN: 'c3Nkc3NkMjMu'
  KEYCLOAK_ADMIN_PASSWORD: 'c3Nkc3NkMjMu'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: gcr.io/uninastream/keycloak
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: keycloak-config
        - secretRef:
            name: keycloak-secret
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
  - name: http
    port: 80
    targetPort: 8080
