apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  VAULT_ADDR: 'http://0.0.0.0:8200'
  VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true, "api_addr": "http://0.0.0.0:8200", "cluster_addr": "http://0.0.0.0:8201", "disable_mlock": "true"}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-deployment
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: gcr.io/uninastream/vault
        imagePullPolicy: Always
        ports:
        - containerPort: 8200
        envFrom:
        - configMapRef:
            name: vault-config
        resources:
          limits:
            cpu: 500m
            memory: 4Gi
          requests:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - name: vault-file
          mountPath: /vault/file
      volumes:
      - name: vault-file
        persistentVolumeClaim:
          claimName: vault-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  selector:
    app: vault
  ports:
  - name: http
    port: 80
    targetPort: 8200
